theme: jekyll-theme-minimal
title: A. Berke Gökmen
description: <head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-1FL4E7ECPD"></script>
  <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-1FL4E7ECPD');
  </script>
  </head>

  <div>
  <i class="material-icons" style="vertical-align:middle">pages</i> <a href="Blog">Blog</a>
  </div>

  <div>
  <i class="material-icons" style="vertical-align:middle">email</i> berke.gokmen@ug.bilkent.edu.tr
  </div>

  <div>
  <i class="material-icons" style="vertical-align:middle">camera_front</i> <a href="https://www.linkedin.com/in/berkegokmen/">LinkedIn</a>
  </div>

  <div>
  <i class="material-icons" style="vertical-align:middle">school</i> <a href="https://scholar.google.com.tr/citations?user=rg7Vk-gAAAAJ&hl=tr">Google Scholar</a>
  </div>

plugins:
  - jekyll-gist
  - jekyll-twitter-plugin
  - jekyll-seo-tag
